# Generated by Django 4.0.2 on 2024-02-04 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ichacksite2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ichacksite2.taskbank'),
        ),
    ]
